[2022-12-27 21:43:26,490] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T21:41:21.176519+00:00 [queued]>
[2022-12-27 21:43:26,496] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T21:41:21.176519+00:00 [queued]>
[2022-12-27 21:43:26,497] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 21:43:26,497] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-27 21:43:26,498] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 21:43:26,506] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_data> on 2022-12-27 21:41:21.176519+00:00
[2022-12-27 21:43:26,511] {standard_task_runner.py:52} INFO - Started process 9999 to run task
[2022-12-27 21:43:26,515] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'transform_data', 'scheduled__2022-12-27T21:41:21.176519+00:00', '--job-id', '525', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmpo111ktlu', '--error-file', '/tmp/tmp5j1fv049']
[2022-12-27 21:43:26,516] {standard_task_runner.py:80} INFO - Job 525: Subtask transform_data
[2022-12-27 21:43:26,570] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T21:41:21.176519+00:00 [running]> on host 8fbeee8d3d5a
[2022-12-27 21:43:26,635] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T21:41:21.176519+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-27T21:41:21.176519+00:00
[2022-12-27 21:43:26,666] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 51, in _transform_parking_data
    df.drop()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 4913, in drop
    errors=errors,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4143, in drop
    "Need to specify at least one of 'labels', 'index' or 'columns'"
ValueError: Need to specify at least one of 'labels', 'index' or 'columns'
[2022-12-27 21:43:26,681] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=transform_data, execution_date=20221227T214121, start_date=20221227T214326, end_date=20221227T214326
[2022-12-27 21:43:26,689] {standard_task_runner.py:97} ERROR - Failed to execute job 525 for task transform_data (Need to specify at least one of 'labels', 'index' or 'columns'; 9999)
[2022-12-27 21:43:26,728] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-27 21:43:26,758] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
