[2024-10-20 12:59:32,785] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.create_table scheduled__2024-10-20T12:52:27.854952+00:00 [queued]>
[2024-10-20 12:59:32,806] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.create_table scheduled__2024-10-20T12:52:27.854952+00:00 [queued]>
[2024-10-20 12:59:32,807] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-20 12:59:32,807] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-20 12:59:32,808] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-20 12:59:32,833] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2024-10-20 12:52:27.854952+00:00
[2024-10-20 12:59:32,843] {standard_task_runner.py:52} INFO - Started process 713 to run task
[2024-10-20 12:59:32,846] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'create_table', 'scheduled__2024-10-20T12:52:27.854952+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmpjms4wkh5', '--error-file', '/tmp/tmpywa8f0hv']
[2024-10-20 12:59:32,847] {standard_task_runner.py:80} INFO - Job 15: Subtask create_table
[2024-10-20 12:59:32,928] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.create_table scheduled__2024-10-20T12:52:27.854952+00:00 [running]> on host 1fca498fbeb9
[2024-10-20 12:59:33,042] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-10-20T12:52:27.854952+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-20T12:52:27.854952+00:00
[2024-10-20 12:59:33,071] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2024-10-20 12:59:33,078] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=create_table, execution_date=20241020T125227, start_date=20241020T125932, end_date=20241020T125933
[2024-10-20 12:59:33,094] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task create_table (The conn_id `postgres` isn't defined; 713)
[2024-10-20 12:59:33,143] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-20 12:59:33,211] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
