[2024-10-20 12:52:15,821] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.is_api_available manual__2024-10-20T12:52:14.142718+00:00 [queued]>
[2024-10-20 12:52:15,841] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.is_api_available manual__2024-10-20T12:52:14.142718+00:00 [queued]>
[2024-10-20 12:52:15,842] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-20 12:52:15,853] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-20 12:52:15,853] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-20 12:52:15,877] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-10-20 12:52:14.142718+00:00
[2024-10-20 12:52:15,886] {standard_task_runner.py:52} INFO - Started process 362 to run task
[2024-10-20 12:52:15,890] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'is_api_available', 'manual__2024-10-20T12:52:14.142718+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmpjpiih13k', '--error-file', '/tmp/tmp9mb872fo']
[2024-10-20 12:52:15,891] {standard_task_runner.py:80} INFO - Job 6: Subtask is_api_available
[2024-10-20 12:52:15,966] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.is_api_available manual__2024-10-20T12:52:14.142718+00:00 [running]> on host 1fca498fbeb9
[2024-10-20 12:52:16,081] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-10-20T12:52:14.142718+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-20T12:52:14.142718+00:00
[2024-10-20 12:52:16,083] {http.py:97} INFO - Poking: 
[2024-10-20 12:52:16,112] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 112, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 103, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 114, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `is_api_available` isn't defined
[2024-10-20 12:52:16,118] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=is_api_available, execution_date=20241020T125214, start_date=20241020T125215, end_date=20241020T125216
[2024-10-20 12:52:16,137] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task is_api_available (The conn_id `is_api_available` isn't defined; 362)
[2024-10-20 12:52:16,183] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-20 12:52:16,248] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
