[2022-12-27 21:05:07,616] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T21:00:01.760381+00:00 [queued]>
[2022-12-27 21:05:07,623] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T21:00:01.760381+00:00 [queued]>
[2022-12-27 21:05:07,624] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 21:05:07,624] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-12-27 21:05:07,625] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 21:05:07,634] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_data> on 2022-12-27 21:00:01.760381+00:00
[2022-12-27 21:05:07,641] {standard_task_runner.py:52} INFO - Started process 8634 to run task
[2022-12-27 21:05:07,646] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'transform_data', 'manual__2022-12-27T21:00:01.760381+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmp6hfjkksb', '--error-file', '/tmp/tmphs5qjybl']
[2022-12-27 21:05:07,647] {standard_task_runner.py:80} INFO - Job 400: Subtask transform_data
[2022-12-27 21:05:07,708] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T21:00:01.760381+00:00 [running]> on host 8fbeee8d3d5a
[2022-12-27 21:05:07,770] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T21:00:01.760381+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T21:00:01.760381+00:00
[2022-12-27 21:05:07,786] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 38, in _transform_parking_data
    df = pd.json_normalize(jsonDict['parkingTransactionKey'])
TypeError: list indices must be integers or slices, not str
[2022-12-27 21:05:07,799] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parking_pipeline, task_id=transform_data, execution_date=20221227T210001, start_date=20221227T210507, end_date=20221227T210507
[2022-12-27 21:05:07,807] {standard_task_runner.py:97} ERROR - Failed to execute job 400 for task transform_data (list indices must be integers or slices, not str; 8634)
[2022-12-27 21:05:07,820] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-27 21:05:07,850] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
