[2022-12-23T22:32:37.741+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-23T22:30:33.152166+00:00 [queued]>
[2022-12-23T22:32:37.748+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-23T22:30:33.152166+00:00 [queued]>
[2022-12-23T22:32:37.749+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-23T22:32:37.750+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-23T22:32:37.750+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-23T22:32:37.761+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_data> on 2022-12-23 22:30:33.152166+00:00
[2022-12-23T22:32:37.766+0000] {standard_task_runner.py:55} INFO - Started process 416 to run task
[2022-12-23T22:32:37.771+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'transform_data', 'scheduled__2022-12-23T22:30:33.152166+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmpv56vhww6']
[2022-12-23T22:32:37.773+0000] {standard_task_runner.py:83} INFO - Job 124: Subtask transform_data
[2022-12-23T22:32:37.975+0000] {task_command.py:389} INFO - Running <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-23T22:30:33.152166+00:00 [running]> on host 1437489fb73b
[2022-12-23T22:32:38.036+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-23T22:30:33.152166+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-23T22:30:33.152166+00:00
[2022-12-23T22:32:38.050+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 28, in process_parking_data
    df = pd.read_json(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 607, in read_json
    encoding_errors=encoding_errors,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 675, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 718, in _get_data_from_filepath
    errors=self.encoding_errors,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 396, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
[2022-12-23T22:32:38.063+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=transform_data, execution_date=20221223T223033, start_date=20221223T223237, end_date=20221223T223238
[2022-12-23T22:32:38.072+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 124 for task transform_data (Invalid file path or buffer object type: <class 'list'>; 416)
[2022-12-23T22:32:38.103+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-23T22:32:38.121+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
