[2022-12-23T22:30:33.501+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-23T22:28:27.160340+00:00 [queued]>
[2022-12-23T22:30:33.508+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-23T22:28:27.160340+00:00 [queued]>
[2022-12-23T22:30:33.509+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-23T22:30:33.510+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-23T22:30:33.510+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-23T22:30:33.520+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_data> on 2022-12-23 22:28:27.160340+00:00
[2022-12-23T22:30:33.525+0000] {standard_task_runner.py:55} INFO - Started process 236 to run task
[2022-12-23T22:30:33.530+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'transform_data', 'scheduled__2022-12-23T22:28:27.160340+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmp5z6eh3ny']
[2022-12-23T22:30:33.533+0000] {standard_task_runner.py:83} INFO - Job 116: Subtask transform_data
[2022-12-23T22:30:33.737+0000] {task_command.py:389} INFO - Running <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-23T22:28:27.160340+00:00 [running]> on host 1437489fb73b
[2022-12-23T22:30:33.797+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-23T22:28:27.160340+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-23T22:28:27.160340+00:00
[2022-12-23T22:30:33.810+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 28, in process_parking_data
    df = pd.read_json(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 607, in read_json
    encoding_errors=encoding_errors,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 675, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 718, in _get_data_from_filepath
    errors=self.encoding_errors,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 396, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
[2022-12-23T22:30:33.820+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=transform_data, execution_date=20221223T222827, start_date=20221223T223033, end_date=20221223T223033
[2022-12-23T22:30:33.828+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 116 for task transform_data (Invalid file path or buffer object type: <class 'list'>; 236)
[2022-12-23T22:30:33.861+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-23T22:30:33.878+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
