[2022-12-27 20:51:55,904] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T20:51:51.382123+00:00 [queued]>
[2022-12-27 20:51:55,911] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T20:51:51.382123+00:00 [queued]>
[2022-12-27 20:51:55,911] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 20:51:55,912] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-27 20:51:55,912] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 20:51:55,922] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_data> on 2022-12-27 20:51:51.382123+00:00
[2022-12-27 20:51:55,926] {standard_task_runner.py:52} INFO - Started process 7696 to run task
[2022-12-27 20:51:55,930] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'transform_data', 'manual__2022-12-27T20:51:51.382123+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmp0rgh9g7p', '--error-file', '/tmp/tmpqmgnjau1']
[2022-12-27 20:51:55,932] {standard_task_runner.py:80} INFO - Job 301: Subtask transform_data
[2022-12-27 20:51:55,982] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T20:51:51.382123+00:00 [running]> on host 8fbeee8d3d5a
[2022-12-27 20:51:56,039] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T20:51:51.382123+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T20:51:51.382123+00:00
[2022-12-27 20:51:56,052] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 37, in _transform_parking_data
    df = pd.json_normalize(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_normalize.py", line 423, in _json_normalize
    raise NotImplementedError
NotImplementedError
[2022-12-27 20:51:56,064] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=transform_data, execution_date=20221227T205151, start_date=20221227T205155, end_date=20221227T205156
[2022-12-27 20:51:56,071] {standard_task_runner.py:97} ERROR - Failed to execute job 301 for task transform_data (; 7696)
[2022-12-27 20:51:56,103] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-27 20:51:56,133] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
