[2024-10-29 02:51:04,713] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.load_data scheduled__2024-10-29T02:26:36.903345+00:00 [queued]>
[2024-10-29 02:51:04,741] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.load_data scheduled__2024-10-29T02:26:36.903345+00:00 [queued]>
[2024-10-29 02:51:04,742] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 02:51:04,744] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-29 02:51:04,744] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-29 02:51:04,777] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-29 02:26:36.903345+00:00
[2024-10-29 02:51:04,787] {standard_task_runner.py:52} INFO - Started process 99 to run task
[2024-10-29 02:51:04,793] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'load_data', 'scheduled__2024-10-29T02:26:36.903345+00:00', '--job-id', '630', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmpeozlrp59', '--error-file', '/tmp/tmpz1_otudn']
[2024-10-29 02:51:04,795] {standard_task_runner.py:80} INFO - Job 630: Subtask load_data
[2024-10-29 02:51:04,900] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.load_data scheduled__2024-10-29T02:26:36.903345+00:00 [running]> on host 6da7af54a32a
[2024-10-29 02:51:05,004] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2024-10-29T02:26:36.903345+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-29T02:26:36.903345+00:00
[2024-10-29 02:51:05,017] {postgres.py:127} INFO - Running copy expert: COPY parking_data FROM stdin WITH DELIMITER as ',', filename: ./tmp/processed_parking_data_00.csv
[2024-10-29 02:51:05,018] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 113, in _load_parking_data
    filename=filename
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 129, in copy_expert
    with open(filename, 'w'):
FileNotFoundError: [Errno 2] No such file or directory: './tmp/processed_parking_data_00.csv'
[2024-10-29 02:51:05,034] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=load_data, execution_date=20241029T022636, start_date=20241029T025104, end_date=20241029T025105
[2024-10-29 02:51:05,050] {standard_task_runner.py:97} ERROR - Failed to execute job 630 for task load_data ([Errno 2] No such file or directory: './tmp/processed_parking_data_00.csv'; 99)
[2024-10-29 02:51:05,085] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-10-29 02:51:05,135] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
