[2022-12-27 20:53:02,933] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T20:47:56.025919+00:00 [queued]>
[2022-12-27 20:53:02,941] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T20:47:56.025919+00:00 [queued]>
[2022-12-27 20:53:02,941] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 20:53:02,942] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-12-27 20:53:02,943] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 20:53:02,952] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_data> on 2022-12-27 20:47:56.025919+00:00
[2022-12-27 20:53:02,957] {standard_task_runner.py:52} INFO - Started process 7754 to run task
[2022-12-27 20:53:02,961] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'transform_data', 'manual__2022-12-27T20:47:56.025919+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmprnwx_4di', '--error-file', '/tmp/tmpcf_1q570']
[2022-12-27 20:53:02,967] {standard_task_runner.py:80} INFO - Job 302: Subtask transform_data
[2022-12-27 20:53:03,023] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.transform_data manual__2022-12-27T20:47:56.025919+00:00 [running]> on host 8fbeee8d3d5a
[2022-12-27 20:53:03,098] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T20:47:56.025919+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T20:47:56.025919+00:00
[2022-12-27 20:53:03,113] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 37, in _transform_parking_data
    df = pd.json_normalize(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_normalize.py", line 423, in _json_normalize
    raise NotImplementedError
NotImplementedError
[2022-12-27 20:53:03,128] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parking_pipeline, task_id=transform_data, execution_date=20221227T204756, start_date=20221227T205302, end_date=20221227T205303
[2022-12-27 20:53:03,136] {standard_task_runner.py:97} ERROR - Failed to execute job 302 for task transform_data (; 7754)
[2022-12-27 20:53:03,175] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-27 20:53:03,212] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
