[2022-12-27 19:16:17,452] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T19:14:14.017514+00:00 [queued]>
[2022-12-27 19:16:17,458] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T19:14:14.017514+00:00 [queued]>
[2022-12-27 19:16:17,459] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 19:16:17,459] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-27 19:16:17,460] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 19:16:17,469] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform_data> on 2022-12-27 19:14:14.017514+00:00
[2022-12-27 19:16:17,473] {standard_task_runner.py:52} INFO - Started process 2399 to run task
[2022-12-27 19:16:17,477] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parking_pipeline', 'transform_data', 'scheduled__2022-12-27T19:14:14.017514+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/parking_dag.py', '--cfg-path', '/tmp/tmpl4m2vwbh', '--error-file', '/tmp/tmphufwdkv2']
[2022-12-27 19:16:17,478] {standard_task_runner.py:80} INFO - Job 97: Subtask transform_data
[2022-12-27 19:16:17,532] {task_command.py:369} INFO - Running <TaskInstance: parking_pipeline.transform_data scheduled__2022-12-27T19:14:14.017514+00:00 [running]> on host 8fbeee8d3d5a
[2022-12-27 19:16:17,590] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=parking_pipeline
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T19:14:14.017514+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-27T19:14:14.017514+00:00
[2022-12-27 19:16:17,593] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parking_dag.py", line 30, in _transform_parking_data
    parking_data = pd.read_csv('data/parking_20221223.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data/parking_20221223.csv'
[2022-12-27 19:16:17,606] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parking_pipeline, task_id=transform_data, execution_date=20221227T191414, start_date=20221227T191617, end_date=20221227T191617
[2022-12-27 19:16:17,613] {standard_task_runner.py:97} ERROR - Failed to execute job 97 for task transform_data ([Errno 2] No such file or directory: 'data/parking_20221223.csv'; 2399)
[2022-12-27 19:16:17,651] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-27 19:16:17,682] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
